### ISSUE TITLE
Character creation screen

### ISSUE THREAD

**Issue by pakalbekim** [pakalbekim/armaldia#103]
Show visually why one class is better than the other

**Comment by pakalbekim** [comment]
Show visually why one class is better than the other

**Comment by AugustinasK** [comment]
I suggest making a working prototype
Also, found an iteresting solution to a coloring of things, pure css:
http://codemyui.com/post/132790351310/color-manipulation-on-images-using-input-type

**Comment by pakalbekim** [comment]
Woow, that tool looks pretty amazing... If you can draw images with one changable color that would be awesome! 

What do you mean by making a prototype? A mockup page how character creation would look like?

**Comment by pakalbekim** [comment]
Merged with #67
