### ISSUE TITLE
Add CSS for inactive and disabled classes for mine-self and cut-trees

### ISSUE THREAD

**Issue by Ewaldaz** [pakalbekim/armaldia#127]
After clicking to mine self or cut trees by yourself "inactive" class is added during the cutting/mining process.
When mine/forest is depleted "disabled" class is added.

Add CSS to visually show that buttons are not clickable.

**Comment by AugustinasK** [comment]
I think it's not clear yet why these buttons are disabled, i suggest adding another div in button with text "DEPLETED" or similiar to make it clear

**Comment by pakalbekim** [comment]
@Ewaldaz We need to cover a few more scenarios. These are the things I have noticed in lumbering (probably would be the same in mining as well):
- "Cut trees" button is not disabled when there is not enough energy. If you calculate required energy on the go, after the click, then I guess there is not easy to fix this and we can forget about it
- "Cut trees" button disappears when the last tree is cut, but is back again after refresh.

Some requests from Augis: "į mine ir cut yourself buttonus tą patį tik ne skaičių o DEPLETED"

**Comment by AugustinasK** [comment]
Could you write what needs to be done here? Not clear

**Comment by pakalbekim** [comment]
I think it's done, Evaldas (or you?) added basic greyed-out style for inactive buttons and "stop" cursor. I'm closing this - you will go through these screens again anyway at some point, then you can add some more styling if you wish.
