### ISSUE TITLE
Possible bug in maximum food that can be eaten calculation (fridge screen)

### ISSUE THREAD

**Issue by pakalbekim** [pakalbekim/armaldia#130]
I can only eat maximum 3 mash potatoes from the fridge, but from the queue I can eat more. Also, my hunger was 0, so it doesn't seem right - I have to eat 3, then 3 more and every time it's less and less efficient even though I'm still starving. Also, maybe reduce penalties a bit, it seems harsh

**Comment by Ewaldaz** [comment]
Fixed bug with queued food.
Penalty is 5% for each food unit.
5 food units can be eaten at once, left that one like it was.
