### ISSUE TITLE
Stat icons in passport should have titles nearby

### ISSUE THREAD

**Issue by AugustinasK** [pakalbekim/armaldia#148]

**Comment by pakalbekim** [comment]
![12607183_10205382190698229_1077149272_n](https://cloud.githubusercontent.com/assets/3639399/12658080/f0089bd8-c617-11e5-9855-f4dc0be2201a.jpg)

Augis: tik value ant to bar'o uždėt, pliusą į žalią mygtuką, to bar'o color geriausia iš ikonų paimt

**Comment by pakalbekim** [comment]
@AugustinasK I just added the title as this was the request from the users. In your version you want to add a bar and remove the actual numbers - I think we need to show the exact values as this is the only place where user can see that - pretty much all other areas have rounded values plus he add skill points here, might be usefull to know the numbers. We can add the bar anyway, but you have to redesign some time in the future.

**Comment by AugustinasK** [comment]
hey, i mentioned that we should add actual values ON TOP of the bars, not
to remove them completely. So if u added titles & bars i can continue
styling this screen

2016-01-31 20:22 GMT+02:00 Arminas Kazlauskas notifications@github.com:
