### ISSUE TITLE
Business center is too empty when LVL<5 AND/OR no company is created. 

### ISSUE THREAD

**Issue by AugustinasK** [pakalbekim/armaldia#149]
More content should be added explaining the company creation mechanics especially for those below LVL 5

**Comment by pakalbekim** [comment]
So we just add some explanation text or some graphics as well? @AugustinasK

**Comment by pakalbekim** [comment]
Create a stop icon with text "reach LVL5" and block business center

**Comment by pakalbekim** [comment]
Workaround created
