### ISSUE TITLE
When clicked on THUMBS-UP in Rate a Blueprint screen, item suddenly disappeared without any explaination.

### ISSUE THREAD

**Issue by AugustinasK** [pakalbekim/armaldia#152]
It disappeared both from voter's view and from blueprint creator's view

**Comment by AugustinasK** [comment]
Ooops, i just realized that this may be intended in BETA version. Close task if so

**Comment by pakalbekim** [comment]
Yep, you are an admin, so you confirm the blueprint immediately. Others just upvote it.
