### ISSUE TITLE
Show how many items can be manufactured with current materials (manufacturing screen)

### ISSUE THREAD

**Issue by pakalbekim** [pakalbekim/armaldia#163]
Very hard to produce items with slots and time restrains, when you dont know this info

**Comment by Ewaldaz** [comment]
Left: Recalculations after manufacturing or adding contract.

**Comment by pakalbekim** [comment]
I think user should see how many he can make right away, without the need of clicking on materials tab. Plus now it's not visible when you want to manufacture something (popup goes over). Possible solutions: move that number near the item name, near the tabs or near the space div on the image.

**Comment by AugustinasK** [comment]
I suggest just adding amount like this: (3)
in manufacturing button
2016 saus. 30 20:42 "Arminas Kazlauskas" notifications@github.com rašė:

**Comment by pakalbekim** [comment]
Simple, I like it. But then I suggest to leave the current version in material tab as well, just as an explanation.
