### ISSUE TITLE
Can't build farm on countryside landtype, not showing up in selection menu

### ISSUE THREAD

**Issue by AugustinasK** [pakalbekim/armaldia#171]
![image](https://cloud.githubusercontent.com/assets/7655035/12660940/68e75484-c61f-11e5-90a8-e0e48c362423.png)

**Comment by AugustinasK** [comment]
This is also true with all the other possible farm landtypes, no options are listed at all

![image](https://cloud.githubusercontent.com/assets/7655035/12661009/dcad060c-c61f-11e5-9428-c251ce43692e.png)
![image](https://cloud.githubusercontent.com/assets/7655035/12661031/f8449ce0-c61f-11e5-8673-e5b25f18e99d.png)

**Comment by AugustinasK** [comment]
Figured out it was because i didn't have a permit.. Really not clear concept of buying and using lands, yet.

**Comment by pakalbekim** [comment]
Yeah, we will need to rethink this land buy stuff. Next time you can close it yourself if you figured out the issue :)

**Comment by AugustinasK** [comment]
Maybe it should be renamed ar grouped with other task regarding company
lands screen
2016 saus. 29 17:52 "Arminas Kazlauskas" notifications@github.com rašė:
