### ISSUE TITLE
Investigate possibilities to get some funding

### ISSUE THREAD

**Issue by Ewaldaz** [pakalbekim/armaldia#195]
Deadline is 3d of March.
More info - http://kurybiskaeuropa.eu/media/artimiausi-terminai/video-zaidimai

EU page with I guess proper deadline:
https://eacea.ec.europa.eu/creative-europe/funding/development-video-games-2016_en
https://eacea.ec.europa.eu/sites/eacea-site/files/eacea_2015_01180000_lt_tra.docx

Last year: https://eacea.ec.europa.eu/creative-europe/selection-results/media-development-european-video-games_en

**Comment by pakalbekim** [comment]
Can't apply because of:

Applicants must

```
prove they have produced a video-game which has been commercially distributed during the two years preceding the call;
present a sales report;
own the majority of the rights related to the submitted project.
```
