### ISSUE TITLE
Company overview space bug

### ISSUE THREAD

**Issue by pakalbekim** [pakalbekim/armaldia#198]
Could be related to rounding fix you applied before
![2016_02_01_21_45_432903948](https://cloud.githubusercontent.com/assets/3639399/12743283/09671b8e-c99e-11e5-971c-ac0300229a39.png)

**Comment by Ewaldaz** [comment]
Whats wrong with this one?

**Comment by pakalbekim** [comment]
Wrong screenshot, it was scrolled down and that issue I think you fixed it. Marijus cannot replicate again this one.
