### ISSUE TITLE
Factory space rounding issue

### ISSUE THREAD

**Issue by pakalbekim** [pakalbekim/armaldia#199]
![2016_02_01_21_47_162543041](https://cloud.githubusercontent.com/assets/3639399/12743440/fa3b0c1e-c99e-11e5-92dc-d2ddba10ed3c.png)

**Comment by Ewaldaz** [comment]
Kada šitas reportintas buvo? padaraiu roundoingą vakar ir čia, ir company overview.

**Comment by pakalbekim** [comment]
Reportintas 2016_02_01_21_47, jei padarei jau po to - closink

**Comment by Ewaldaz** [comment]
Sufixinau ir JS
