### ISSUE TITLE
FB/twitter registration problems

### ISSUE THREAD

**Issue by pakalbekim** [pakalbekim/armaldia#211]
Maybe we should remove twitter login at all? It doesn't make much sense to login with normal email and then use twitter next time. I doubt many people would use this scenario. Don't worry about this task too much, do the other ones first, there are plenty of people that used FB successfully for sign up.

Steps to replicate from Marijus: "paspaude logintis per fb, ismete pradziai kad kazka suvest, suvede, pist ismete error, kad ale twiteris neprovidina emailo"

![12695168_1069203473143767_1444284457_o](https://cloud.githubusercontent.com/assets/3639399/12868131/2b8f93aa-cd11-11e5-9ed6-3bd7cfc258ff.jpg)
![12696666_1069201943143920_519111572_o](https://cloud.githubusercontent.com/assets/3639399/12868132/2bf94a20-cd11-11e5-840a-0967c42f3216.jpg)

**Comment by AugustinasK** [comment]
I agree that we should remove twitter login option for now, at least until things are fixed
