### ISSUE TITLE
Market and manufacturing css issues after responsiveness update

### ISSUE THREAD

**Issue by pakalbekim** [pakalbekim/armaldia#224]
- Text "for" is not visible when buying an item
- There is no "Buy" button in blueprint shop
- Filters are misaligned (see screenshot)
  ![screenshot-armaldia com 2016-02-08 17-47-16](https://cloud.githubusercontent.com/assets/3639399/12888604/0552a69c-ce8c-11e5-9b50-6a765df8c172.png)
- Marijus: I buy a thing, and some shit happens. Item goes to inventory, but empty space flattens. 
  ![2016_02_08_12_20_914522576](https://cloud.githubusercontent.com/assets/3639399/12888643/30e68bf2-ce8c-11e5-847f-158e50b6591e.png)
- Wonderas: Nesimato dešinėj pusej manufacture button, neiseina pradet manufactorint ant mobilaus. Prieš tai viskas puikiai buvo
  ![manufacture](https://cloud.githubusercontent.com/assets/3639399/12888687/57cd935a-ce8c-11e5-84c0-ac8d16fc10d7.png)

**Comment by AugustinasK** [comment]
Merged with #223
