### ISSUE TITLE
Market doesnt have item prices

### ISSUE THREAD

**Issue by pakalbekim** [pakalbekim/armaldia#232]
Could be because html changed in "My inventory" tab where user is selling
![2016_02_08_20_22_402480462](https://cloud.githubusercontent.com/assets/3639399/12960570/f682a924-d04c-11e5-8cbc-c4167cddd43d.png)

**Comment by AugustinasK** [comment]
This issue is possibly done by @Ewaldaz , could not replicate

**Comment by pakalbekim** [comment]
I have replicated it. The price is not shown on "My items on sale" tab when adding a new item on sale.

**Comment by Ewaldaz** [comment]
I added that price for items in sale, so it was missing JS stuff.
