### ISSUE TITLE
Items disappeared after saving them

### ISSUE THREAD

**Issue by pakalbekim** [pakalbekim/armaldia#233]
Justina: Nusipirkau aš kardą už 5500 ir dar anksčiau nusipirkau sandalus ir apsiaustą, nežinau kiek kainavo. Galvojau susidėsiu ant savo žmogeliuko. Susidėjau, paspaudžiau išsaugoti ir man išmetė raudoną lentelę viršuj, neišsisaugojo ir pasišalino tie sudėti daiktai. Carbon fiber sword 5500 coat "snow" 3300 Sandals "gladiator's kick"789

Steps:
1. Store item icona paspaudi
2. Cancel
3. Bandai uzsidet kazka - nieko nevyksta
4. Reload - perkele daiktus i storage

**Comment by Ewaldaz** [comment]
Check items in storage.
I got similar thing - I wanted to equip items, but they disappeared (no hacking warning).
After reload checked storage - and there they were.
Put them back from storage and equipped normally.
