### ISSUE TITLE
Hunger is not restored fast enough

### ISSUE THREAD

**Issue by pakalbekim** [pakalbekim/armaldia#237]
When I play, I'm constantly hungry. Stamina, energy and health are regenerated really fast (I have a few items that improve this, but still), while hunger is always down and stops me form playing. Last night I refilled the fridge with Strawberry jam (+3 hunger), this morning I had only 13 hunger and I cannot play much - food efficiency is killing me and regenerate rate is slow.

I think this situation rises from several factors, that might include:
- There are items that regenerate stats, but not hunger, so there is a big difference
- Food efficiency is effecting the food automatic eating
- The food amount eaten per cronjob is too small
- The cronjob takes efficiency into account which it shouldn't
- Can we renegerate hunger every 5 mins as well? Like all other stats, not it's a bit inconsistent...

Some more info: I have food in the fridge, my food efficiency is 65%, I got +1 hunger in 1 hour

**Comment by Ewaldaz** [comment]
Food efficiency decrease have been reduced 5 times;
Amount of food possible for consumption at once have been increased 2 times;
Checked cronjobs - efficiency is not taken into account;
As discussed with Arminas amount of food eaten at once during the cronjob and cronjob runtime stays the same;
