### ISSUE TITLE
Energy, strength and other limits are not added after equipping the Crown

### ISSUE THREAD

**Issue by pakalbekim** [pakalbekim/armaldia#243]

**Comment by Ewaldaz** [comment]
most of the bonuses are added for all items in your inventory, not only those that you are wearing. Only exception is Fight Attack/Defense bonus. Probably equippable items should give bonus only when they are equipped.

**Comment by pakalbekim** [comment]
Yes, that is exactly the problem and yes they should only give you bonuses
when equipped.

On Mon, Feb 15, 2016 at 12:11 PM, Evaldas notifications@github.com wrote:

> most of the bonuses are added for all items in your inventory, not only
> those that you are wearing. Only exception is Fight Attack/Defense bonus.
> Probably equippable items should give bonus only when they are equipped.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pakalbekim/armaldia/issues/243#issuecomment-184123850
> .

## 

Best regards,
Arminas Kazlauskas
