### ISSUE TITLE
Negative reserved quantity in warehouse

### ISSUE THREAD

**Issue by pakalbekim** [pakalbekim/armaldia#274]
I just noticed it as some point, have Zinc and Aluminum negative reserved quantity. I was manufacturing items, that use those metals, maybe there is an error in how it is deducted after someone finishes a contract or I cancel a contract (not added back for example). I also put those metals on sale and then moved them back after a few days, but that might not be related
![screenshot-www armaldia com 2016-02-19 19-39-12](https://cloud.githubusercontent.com/assets/3639399/13182000/b7b039fa-d740-11e5-9bdf-06439896b42d.png)

**Comment by Ewaldaz** [comment]
Cannot reproduce, clearly Aragorn hacked something in DB :D
