### ISSUE TITLE
Double check if trader groups items (for the same price)

### ISSUE THREAD

**Issue by pakalbekim** [pakalbekim/armaldia#285]
Found this, might be old stuff, just double check
![screenshot-www armaldia com 2016-02-21 11-58-49](https://cloud.githubusercontent.com/assets/3639399/13201817/9df25c02-d892-11e5-9dbe-c7ab2c318a5f.png)

**Comment by Ewaldaz** [comment]
It was not... Price was float, so it did not found such a record. Fixed!
