### ISSUE TITLE
Killing animal starts the cycle again

### ISSUE THREAD

**Issue by pakalbekim** [pakalbekim/armaldia#296]
I have been growing lion for 7 days, after the kill I saw a message about collected materials and saw the lion growing again. Which is nice for me, but should be, right? :) Same after refresh.
![screenshot-www armaldia com 2016-02-23 21-39-01](https://cloud.githubusercontent.com/assets/3639399/13262464/ff38110c-da75-11e5-9cab-8c6b3e10d55d.png)

Update: It didn't happen with Alligators

**Comment by Ewaldaz** [comment]
Cannot reproduce, maybe was one-time glitch
