### ISSUE TITLE
Implement daily tasks screen

### ISSUE THREAD

**Issue by Ewaldaz** [pakalbekim/armaldia#91]
Take a shower (replenish some energy), cut the grass (increase mood), clean the dishes (increase mood), do some stretching (increase stamina), brush teeth, wash hands, take a nap, take out garbage, take care of random vegetation around your home (find random stuff)

Play Armaldia on your computer inside the game (inception)

Play Construct 2 game (once a day):
- Furniture moving
- Racing
- Eating game

Implements daily streaks

**Comment by AugustinasK** [comment]
Maybe we should group EAT-SHOWER-CUT GRASS actions ?

**Comment by pakalbekim** [comment]
They should be grouped, i think there should be under daily tasks list
together with various other activity. That is with exception for shower, it
should be visible with a counter all the time and would attract people to
wait a bit more in the game or login more often to collect it every say 6
hours

**Comment by Ewaldaz** [comment]
An idea was to show character's living place in the map and put all of those daily tasks in there. maybe even different tasks for different place, plus randomize them a bit. Probably all of them should be each X hours or one action each X hours, s ousers will not be able to do all of them at once.

**Comment by pakalbekim** [comment]
Then maybe it would make sense to attach them to residence screen? I mean
if you click your living place you should see it at least, not only actions?

**Comment by Ewaldaz** [comment]
Yes, agree on that.
It would be nice to see your actual living place as well.
With endless upgrades possibilities in the future :D

**Comment by pakalbekim** [comment]
Merged with #128
