### ISSUE TITLE
Game news email is not sent

### ISSUE THREAD

**Issue by Ewaldaz** [pakalbekim/armaldia#95]

**Comment by Ewaldaz** [comment]
This is issue with gmail... Seems like it is blocking outgoing emails.

**Comment by pakalbekim** [comment]
We can consider using another provider, e.g. Mailgun has pretty good api
for sending emails, but i dont remember if they give anything for free.

Btw, does that mean users dont get ANY emails now? That would be bad...

**Comment by Ewaldaz** [comment]
First 10k/month is for free, so I think for now it's enough. I will create an account and set armaldia to use mailgun.
Later we will see, there are cheaper alternatives, like this one:
https://www.mandrill.com/pricing/

**Comment by pakalbekim** [comment]
I think you have fixed this one @Ewaldaz ?

**Comment by Ewaldaz** [comment]
Not yet, still in progress :)
