### ISSUE TITLE
Game ocasionally loads blank screen

### ISSUE THREAD

**Issue by Ewaldaz** [pakalbekim/armaldia#96]

**Comment by AugustinasK** [comment]
Ewaldaz i spotted that .actual-content div has set attribute style="display:none", maybe that helps

**Comment by pakalbekim** [comment]
Awesome, kaip sita sufixinai?

On Tue, Nov 17, 2015 at 11:07 PM, Evaldas notifications@github.com wrote:

> Closed #96 https://github.com/pakalbekim/armaldia/issues/96.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pakalbekim/armaldia/issues/96#event-467142021.

## 

Best regards,
Arminas Kazlauskas

**Comment by Ewaldaz** [comment]
Ten trigerrino showToggle, pakeičiau į showDown
